### ISSUE TITLE
onItemClickListener getting  Null Pointer Exception

### ISSUE THREAD

**Issue by kawserahamed** [dangiashish/Auto-Image-Slider#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codebyashish.autoimageslider.Adapter.ViewAdapter.setItemClickListener(com.codebyashish.autoimageslider.Interfaces.ItemsListener)' on a null object reference
                                                                                                    	at com.codebyashish.autoimageslider.AutoImageSlider.onItemClickListener(AutoImageSlider.java:342)
                                                                                                    	at com.syntax.systems.propertymanagment.ui.HomeFragment.onCreateView(HomeFragment.java:71)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:201)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6820)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

**Comment by dangiashish** [comment]
hi @kawserahamed, please re-check that you have initialized the listener callback correctly before overriding the methods. 
`autoImageSlider.onItemClickListener(this);`
also please watch the tutorial carefully - [Add Click Listener On AutoImageSlider](https://www.youtube.com/watch?v=iHlsQ-Ltm0Q)
If nothing worked for you, then feel free to connect with me.
Happy coding :)
